### ISSUE TITLE
Allow scoping per namespace (username / organization)

### ISSUE THREAD

**Issue by jurre** [melvinsh/vcsmap#2]
It would be nice if we could check a single namespace (user or organization) instead of all of github

**Comment by melvinsh** [comment]
I agree. This can be done by adding `user:` or `repo:` to the search query [as documented here](https://help.github.com/articles/searching-code/#search-within-a-users-or-organizations-repositories).

**Comment by jurre** [comment]
Willing to put the work in on this one. I'll try to find time tomorrow

**Comment by melvinsh** [comment]
👍
