### ISSUE TITLE
Fails with latest ruby from rvm

### ISSUE THREAD

**Issue by 0x27** [melvinsh/vcsmap#5]
Not a Ruby guy, so not entirely sure what is going on here. I used `rvm` to get Ruby 2.3.1 and bundler to install the vcsmap dependencies. Anyway, on running vcsmap, I am greeted with a crash currently.

```
$ ruby vcsmap.rb 
/home/sky/tools/vcsmap/lib/plugins/wordpress_config.rb:3:in `<module:Plugin>': uninitialized constant Vcsmap::Plugin::BasePlugin (NameError)
Did you mean?  Vcsmap::Plugin
    from /home/sky/tools/vcsmap/lib/plugins/wordpress_config.rb:2:in `<module:Vcsmap>'
    from /home/sky/tools/vcsmap/lib/plugins/wordpress_config.rb:1:in `<top (required)>'
    from vcsmap.rb:14:in `require_relative'
    from vcsmap.rb:14:in `block in <main>'
    from vcsmap.rb:14:in `glob'
    from vcsmap.rb:14:in `<main>'
$
```

I get the same exception/crash when running the tests shell script.

**Comment by 0x27** [comment]
Update: Removing the "wordpress_config.rb" plugin seems to have solved it. Trying to work out whats wrong in it despite not having done any Ruby stuff since forever. Will update if I work it out :)

**Comment by melvinsh** [comment]
Thanks, I'll investigate too!

**Comment by melvinsh** [comment]
I can confirm the issue. Will push the patch in a couple of minutes.

**Comment by melvinsh** [comment]
@0x27 please `git pull && bundle` and let me know if it worked 😄

**Comment by 0x27** [comment]
Works fine now :)
