### ISSUE TITLE
Load plugins dynamically

### ISSUE THREAD

**Issue by justin-gerhardt** [melvinsh/vcsmap#9]
Please forgive me if I'm incorrect, I don't know ruby. As far as I can tell plugins have to be specified in the hard coded list in plugin_list.rb. This is inconsistent with the README.md which suggests they can be added by placing a file in the plugins folder. Having potentially multiple independent plugins editing a file is sub optimal and a better solution would be to load plugins and their list metadata data automatically from the files included in the plugins folder.

**Comment by melvinsh** [comment]
Hi @justin-gerhardt, thanks. In the README it does say that you have to create an entry in `lib/plugin_list.rb`. This is because the app needs to 'list' and search the plugins. Loading all the plugins individually and compiling a list every time is a lot slower.
